import 'dart:io';

const _generatedHeader = '''// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by tool/generate_app_version.dart from pubspec.yaml.
''';

void main(List<String> arguments) {
  final checkOnly = arguments.length == 1 && arguments.single == '--check';
  if (arguments.isNotEmpty && !checkOnly) {
    stderr.writeln('Usage: dart run tool/generate_app_version.dart [--check]');
    exitCode = 64;
    return;
  }

  final repositoryRoot = File.fromUri(Platform.script).parent.parent;
  final pubspecFile = File(
    '${repositoryRoot.path}${Platform.pathSeparator}pubspec.yaml',
  );
  final outputFile = File(
    '${repositoryRoot.path}${Platform.pathSeparator}lib'
    '${Platform.pathSeparator}core${Platform.pathSeparator}generated'
    '${Platform.pathSeparator}app_version.dart',
  );

  final pubspec = pubspecFile.readAsStringSync();
  final versionMatches = RegExp(
    r'^version:\s*([^\s#]+)\s*(?:#.*)?$',
    multiLine: true,
  ).allMatches(pubspec).toList();

  if (versionMatches.length != 1) {
    stderr.writeln(
      'Expected exactly one top-level version field in ${pubspecFile.path}, '
      'but found ${versionMatches.length}.',
    );
    exitCode = 65;
    return;
  }

  final fullVersion = versionMatches.single.group(1)!;
  final parsedVersion = RegExp(
    r'^(\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?)(?:\+([0-9A-Za-z.]+))?$',
  ).firstMatch(fullVersion);
  if (parsedVersion == null || parsedVersion.group(2) == null) {
    stderr.writeln(
      'Expected version to use semantic-version+build format, but found '
      '"$fullVersion".',
    );
    exitCode = 65;
    return;
  }

  final version = parsedVersion.group(1)!;
  final buildNumber = parsedVersion.group(2)!;
  final generated =
      '''$_generatedHeader
abstract final class GeneratedAppVersion {
  static const String version = '$version';
  static const String buildNumber = '$buildNumber';
  static const String fullVersion = '$fullVersion';
}
''';

  if (checkOnly) {
    if (!outputFile.existsSync() ||
        outputFile.readAsStringSync() != generated) {
      stderr.writeln(
        '${outputFile.path} is out of date. '
        'Run: dart run tool/generate_app_version.dart',
      );
      exitCode = 1;
      return;
    }
    stdout.writeln('Application version metadata is up to date: $fullVersion');
    return;
  }

  outputFile.parent.createSync(recursive: true);
  outputFile.writeAsStringSync(generated);
  stdout.writeln('Generated ${outputFile.path} for $fullVersion');
}
